### ISSUE TITLE
Add Istanbul BFT

### ISSUE THREAD

**Issue by coeniebeyers** [ConsenSys/QuorumNetworkManager#103]
This can be picked up as soon as #101 is done

**Comment by rynobey** [comment]
Follow these steps to set up in IBFT Quorum network:
1. Install go-quorum >= 1.7.2 on all nodes.
2. Install istanbul-tools on at least one node.
3. Generate genesis.json, static-nodes.json templates (and nodekeys) using instanbul-tools on one of the nodes: istanbul setup --nodes --verbose --num <N> --quorum --save (N = number of initial validator nodes).
4. Create chaindata directory on all nodes: mkdir Blockchain
5. Create (empty) passwords file on all nodes: touch passwords.txt
6. Create account(s) on all nodes: geth --datadir Blockchain --password passwords.txt account new > account1.txt
7. Update coinbase address in genesis.json template and allocate eth (using needed accounts in accounts.txt files on all nodes)
8. Copy updated genesis.json to all nodes.
9. Update static-nodes.json with correct IPs and ports, and copy to all nodes into chaindata directory. Cannot change enodes anymore (unless new extraData in genesis.json is generated using istanbul-tools).
10. Initialize chaindata directory on all nodes: geth --datadir Blockchain init genesis.json
11. Make sure each node has the nodekey in Blockchain/geth/nodekey corresponding to its enode in static-nodes.json & extraData.
12. Start geth nodes: nohup geth --datadir Blockchain --unlock 0 --password passwords.txt --mine --minerthreads 1 --syncmode full --shh --port 20000 --rpc --rpcaddr 0.0.0.0 --rpcport 20010 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul &> gethNode.log &

**Comment by coeniebeyers** [comment]
Thanks for this, super useful!
