### ISSUE TITLE
Add the option to start a node using pm2 instead of screen

### ISSUE THREAD

**Issue by coeniebeyers** [ConsenSys/QuorumNetworkManager#112]

**Comment by mnd999** [comment]
The PM2 license (AGPL3) is not compatible with my client's policies. This may be the case with other enterprise users as well - is it the best choice?

**Comment by coeniebeyers** [comment]
Hi! pm2 is just an example of a process manager to use, one should be able to use others (screen should still work). Let me know if there is a specific process manager that doesn't work and I can take a look at making it compatible.
