### ISSUE TITLE
Cannot install without having Github credentials

### ISSUE THREAD

**Issue by Kegsay** [ConsenSys/QuorumNetworkManager#114]
Due to the use of `git://` URIs in `package-lock.json`, it is impossible to `npm install` this project without having Github credentials. 

A blunt swap to `https://` fixes this. Affected lines:
 - https://github.com/ConsenSys/QuorumNetworkManager/blob/35448b2575ed9d6f9766670c2e81b08fce969d7b/package-lock.json#L2518
 - https://github.com/ConsenSys/QuorumNetworkManager/blob/35448b2575ed9d6f9766670c2e81b08fce969d7b/package-lock.json#L2565

**Comment by aaroncolaco** [comment]
Faced this issue too. Submitted a PR. Would be great if you could merge it.
