### ISSUE TITLE
If pm2 restarts a node, it will clear existing files

### ISSUE THREAD

**Issue by coeniebeyers** [ConsenSys/QuorumNetworkManager#121]
Alternatively, one should be able to start pm2 with KEEP_FILES=true. If it restarts the node process, then it will not clear the files.

Unfortunately, this means that one has to first start the node with KEEP_FILES=false to create the desired configuration. Then one has to stop the node and start it using KEEP_FILES=true.

Add checking and creating of files if they are not present. as well as an easy way to clear configuration.

**Comment by mnd999** [comment]
I did something like this:

`config.setup.keepExistingFiles = fs.existsSync('/path/to/QuorumNetworkManager/Blockchain/geth/nodekey');`

**Comment by coeniebeyers** [comment]
Thanks for this!

**Comment by coeniebeyers** [comment]
The QNM will by default backup and restore the Blockchain/keystore folder. If this is unwanted, please pass `DELETE_KEYS=true` to remove all previous account addresses.
