### ISSUE TITLE
Unable to deploy a Smart Contract

### ISSUE THREAD

**Issue by umerjafer** [ConsenSys/QuorumNetworkManager#122]
I have created a Quorum node using Quorum Network Manager. For testing purpose I started a single node using Raft. I am using Nethereum.Quorum to connect the node. 

The node starts without any problem and I am able to connect to it but when I try to deploy a smart contract I get the following error:

{Nethereum.JsonRpc.Client.RpcResponseException: Gas price not 0
   at Nethereum.JsonRpc.Client.RpcClient.HandleRpcError(RpcResponse response)
   at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext()}

When I try to deploy the same smart contract with gas price set to 0, the transaction is submitted and I get the transaction hash but I don't get the transaction receipt. When I checked the logs I found that the transaction failed due to running out of gas. The following is the log in gethNode.log:

INFO [02-25|12:20:23] started whisper v.5.0
INFO [02-25|12:20:23] HTTP endpoint opened: http://0.0.0.0:20010
INFO [02-25|12:20:23] IPC endpoint opened: /home/administrator/QuorumNetworkManager/Blockchain/geth.ipc
INFO [02-25|12:20:23] WebSocket endpoint opened: ws://[::]:20020
INFO [02-25|12:20:23] ignoring expected ConfChangeAddNode for initial peer raft id=1
INFO [02-25|12:20:23] start snapshot                           applied index=0 last snapshot index=0
INFO [02-25|12:20:23] compacted log                            index=0
INFO [02-25|12:20:23] persisted the latest applied index       index=1
INFO [02-25|12:20:24] Unlocked account                         address=0xc2D52185cD77bb66a716Cd7378E9ff28b59991b6
raft2018/02/25 12:20:24 INFO: 1 is starting a new election at term 1
raft2018/02/25 12:20:24 INFO: 1 became candidate at term 2
raft2018/02/25 12:20:24 INFO: 1 received MsgVoteResp from 1 at term 2
raft2018/02/25 12:20:24 INFO: 1 became leader at term 2
raft2018/02/25 12:20:24 INFO: raft.node: 1 elected leader 1 at term 2
INFO [02-25|12:20:24] Not minting a new block since there are no pending transactions
INFO [02-25|12:20:24] persisted the latest applied index       index=2
INFO [02-25|12:24:14] Submitted transaction                    fullhash=0x9be6631f4deb2437cdee8ee71f75850395de68b928$
INFO [02-25|12:24:14] Generated next block                     block num=1 num txes=1
INFO [02-25|12:24:14] 🔨  Mined block                          number=1 hash=2e0ca380      elapsed=1.116187ms
INFO [02-25|12:24:16] Imported new chain segment               blocks=1 txs=1 mgas=0.021 elapsed=2.079s     mgasps=0$
INFO [02-25|12:24:16] persisted the latest applied index       index=3
INFO [02-25|12:24:16] Not minting a new block since there are no pending transactions
WARN [02-25|12:24:52] message loop                             peer=c9a517c17902abd8 err=EOF
WARN [02-25|12:49:47] message loop                             peer=ddbd66c19a456a52 err=EOF
WARN [02-25|12:54:21] message loop                             peer=158f3d8b6314b91a err=EOF
INFO [02-25|12:54:28] Submitted contract creation              fullhash=0xc949a8245be7d3cbd5442bba52f453f5e69482a81f$
INFO [02-25|12:54:28] TX failed, will be removed               hash=c949a8…34e1a6 err="out of gas"
INFO [02-25|12:54:28] Not minting a new block since there are no pending transactions
WARN [02-25|12:55:03] message loop                             peer=158f3d8b6314b91a err=EOF
INFO [02-25|12:58:37] Submitted contract creation              fullhash=0x9d6a5841fa51996dddbc3a91eab46437c979f3217a$
INFO [02-25|12:58:37] TX failed, will be removed               hash=c949a8…34e1a6 err="out of gas"
INFO [02-25|12:58:37] Not minting a new block since there are no pending transactions
INFO [02-25|13:20:20] Regenerated local transaction journal    transactions=2 accounts=1

**Comment by coeniebeyers** [comment]
Hi! Please note that the QNM only handles creating and configuring the node. A contract creation issue is therefore more likely related to the Nethereum, Quorum or Geth projects.

That said, have you tried deploying the contract with more gas? Have you tried deploying a small contract?

**Comment by umerjafer** [comment]
Hi @coeniebeyers ,

Thanks for your response. The problem is related to geth responding with the error:  **Gas price not 0** regardless of the amount of gas passed. I reviewed Quorum repository for the exact error message and I found and an error constant which is used two different places in Quroum. I will post the error on Quorum repository to see what their feedback is.

**Comment by coeniebeyers** [comment]
Hi! No problem :) Hope you are able to solve the issue.

I haven't used Nethereum, but I know when using truffle (which uses web3 under the hood) one has to set `gasPrice: 0` in the `truffle.js` file when using a quorum node.
