### ISSUE TITLE
Generating node key Error

### ISSUE THREAD

**Issue by Max-Pano** [ConsenSys/QuorumNetworkManager#59]
Hi, I want to start some RAFT nodes, and
followed as the steps below
> Option 2: Installing Manually

but got a error with logs:

> [*] Starting new network...
Generating node key
ERROR: I0917 16:55:02.603558 p2p/discover/udp.go:217] Listening, enode://79c2cff29ab5da81d029d5eec7bf8cbda1af3e2f2aedf281b6530fbf530bc4e40cfa6160152161f22e5576187b91c35ecd02fa0a02945b78a46ede62a4acd4ab@[::]:30301

enode: enode://79c2cff29ab5da81d029d5eec7bf8cbda1af3e2f2aedf281b6530fbf530bc4e40cfa6160152161f22e5576187b91c35ecd02fa0a02945b78a46ede62a4acd4ab@172.16.125.51:20000?raftport=40000

Is it a issue? what did I possibly do wrong if not. Thanks for any respond

**Comment by coeniebeyers** [comment]
Hi! Can you confirm that all the correct ports are open?

Also, the two enodes shown have two different ports, the first one shows 30301 and the other one shows 20000, which one is the correct one? By default, the QNM will use 20000

**Comment by coeniebeyers** [comment]
I've not heard anything in a while, can I close this?
