### ISSUE TITLE
Getting an error when trying to set up the QuorumNetworkManager on mac...

### ISSUE THREAD

**Issue by simonmullaney** [ConsenSys/QuorumNetworkManager#66]
`dhcp-892beb96:QuorumNetworkManager simonmullaney$ node index.js 
Trying to get public ip address, please wait a few seconds...
Welcome! 

Please enter the IP address other nodes will use to connect to this node. 

Also, please enter a publicly identifyable string for this node to use.

prompt: localIpAddress:  (137.43.233.40) 
prompt: nodeName:  simon
/Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/util.js:175
    if(result.geth.length > 0){
                  ^

TypeError: Cannot read property 'length' of undefined
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/util.js:175:19
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/async/dist/async.js:3861:9
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/async/dist/async.js:924:17)
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/async/dist/async.js:906:16
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/async/dist/async.js:3858:13
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/util.js:162:9
    at /Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/ps-node/lib/index.js:157:14
    at ChildProcess.<anonymous> (/Users/simonmullaney/Desktop/QuorumNetworkManager/QuorumNetworkManager/node_modules/ps-node/lib/index.js:94:16)
    at emitTwo (events.js:125:13)
`

**Comment by coeniebeyers** [comment]
Hi! That is a pretty strange place for this to happen, it seems like there might be something wrong with running `ps`. Can you confirm the output `which ps` is `/bin/ps` ?

In the meantime I've added extra checks that should help with this issue. Please pull from `master` branch again and see if you get any further.

**Comment by simonmullaney** [comment]
Yes the output of which ps is /bin/ps. Ill pull it from master and let you know how I get on :)

**Comment by simonmullaney** [comment]
Working now, thanks!
