### ISSUE TITLE
Upgrade web3 + whisper + geth to latest versions

### ISSUE THREAD

**Issue by coeniebeyers** [ConsenSys/QuorumNetworkManager#72]
Quorum currently uses geth 1.5, which uses whisper v2 which needs web3 < v1. Quorum is about to upgrade to geth 1.6, which means upgrading to whisper v5 which will need upgrading to web3 >= v1. 

Unfortunately this means all three will have to be upgraded in lockstep. There is likely also going to be other changes, ex. the genesis block util.

**Comment by conor10** [comment]
Is this far off?

**Comment by coeniebeyers** [comment]
Hi! Making good progress on this. This has required a lot of work (you can take a look at the Geth172 branch) - What has been done: Genesis blocks compatible with Geth1.7.2, using web socket rpc rather than http rpc, adding explicit symmetric encryption for whisper subscriptions, new way of then subscribing to new whisper messages. WIP: Posting/sending messages, probably some unknown things as well.
