### ISSUE TITLE
ERROR: Fatal: listen udp :30301: bind: address already in use

### ISSUE THREAD

**Issue by simonmullaney** [ConsenSys/QuorumNetworkManager#90]
Getting this error when trying to set up a raft network. Does anyone have any ideas?

Terminal output:

`
ubuntu@ubuntu-xenial:~/workspace/QuorumNetworkManager$ node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! 

Please enter the IP address other nodes will use to connect to this node. 

Also, please enter a publicly identifyable string for this node to use.

prompt: localIpAddress:  (137.43.232.151) 137.43.232.151
prompt: nodeName:  node1
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
prompt: option:  1
[*] Starting new node...
Generating node key
ERROR: Fatal: listen udp :30301: bind: address already in use

enode: enode://3705fb462405bcf3834d95e0bde008b7e6766e7fd562c15bb7341fb12ca741044db857865b0d877e4659c0f8bde37f2f345a9cf8c54238c62cdb57cca1dd7532@137.43.232.151:20000?raftport=40000

[*] Starting communication node...
`

**Comment by coeniebeyers** [comment]
Hi! This means something is already using port 30301, you can use `lsof -i :30301` to find out more.

**Comment by simonmullaney** [comment]
Got it sorted but now its just hanging  on:  "[*] Starting communication node..."

simon@Node1:~/workspace/QuorumNetworkManager$ node index.js 
Trying to get public ip address, please wait a few seconds...
Welcome! 

Please enter the IP address other nodes will use to connect to this node. 

Also, please enter a publicly identifyable string for this node to use.


prompt: localIpAddress:  (13.82.93.101) 
prompt: nodeName:  raft1
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  5
ERROR: geth: no process found

geth: no process found

ERROR: constellation-node: no process found

constellation-node: no process found

Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
prompt: option:  1
[*] Starting new node...
Generating node key

enode: enode://cb27f8671ff4e7361dc5f5ec0e6de77572bb1d0320a1a5d98f10980f03378c1de33b8085bc2abece8b728b3ba10930c6b3fd4b98b7aa23127c3046bba6abfb67@13.82.93.101:20000?raftport=40000

[*] Starting communication node...

**Comment by coeniebeyers** [comment]
Can you have a look at `communicationNode.log` and let me know what the last couple of lines say?

**Comment by simonmullaney** [comment]
nohup: failed to run command 'geth': No such file or directory

is all thats there...

**Comment by coeniebeyers** [comment]
What is the output of `which geth` in a normal terminal? You might need to source your .bashrc with `source ~/.bashrc`

**Comment by simonmullaney** [comment]
/Users/simonmullaney/Desktop/go/bin/geth

**Comment by simonmullaney** [comment]
Still getting the same error in communicationNode.log - nohup: failed to run command 'geth': No such file or directory

**Comment by coeniebeyers** [comment]
wait, `/Users/simonmullaney/Desktop/go/bin/geth` isn't correct. It should be pointing to something like `/home/coenie/workspace/quorum/build/bin/geth`. Can you confirm that there is a geth binary under `quorum/build/bin/geth` ? If so, do a `mv /Users/simonmullaney/Desktop/go/bin/geth /Users/simonmullaney/Desktop/go/bin/old_geth`

**Comment by simonmullaney** [comment]
I dont have a geth binary at quorum/build/bin/geth

only the following:

Simons-MacBook-Pro:build simonmullaney$ pwd
/Users/simonmullaney/Desktop/quorum/build
Simons-MacBook-Pro:build simonmullaney$ ls
_vendor			ci-notes.md		deb.changelog		deb.copyright		deb.install		env.sh
_workspace		ci.go			deb.control		deb.docs		deb.rules		update-license.go
Simons-MacBook-Pro:build simonmullaney$

**Comment by coeniebeyers** [comment]
That doesn't seem right, you might need to re-download quorum. I have the following:
```
coenie@coenie:~/workspace/quorum/build$ ls
bin    ci-notes.md    deb.control    deb.docs     deb.rules  update-license.go  _workspace
ci.go  deb.changelog  deb.copyright  deb.install  env.sh     _vendor
```
Try the following from your `Desktop` folder:
```
rm -rf quorum
git clone https://github.com/jpmorganchase/quorum.git
cd quorum/
make all
echo "PATH=\$PATH:"$PWD/build/bin >> ~/.bashrc
source ~/.bashrc
```

**Comment by simonmullaney** [comment]
Ok, I did that and now I have the same files as you in quorum/build. I'm still getting the same error when I try to set up the QNM:  nohup: failed to run command 'geth': No such file or directory

The result I get for which geth after doing the above steps is now: /usr/local/bin/geth

**Comment by coeniebeyers** [comment]
Okay, so now it seems like geth is still not pointing to the correct place. It should be pointing to `/Users/simonmullaney/Desktop/quorum/build/bin/geth` (if this is still where you installed quorum to)

To fix this, do a `sudo mv /usr/local/bin/geth /usr/local/bin/geth_old` - this will just rename the old (un quorum-ified) geth binary to geth_old. Let me know what the output of `which geth` is.

**Comment by simonmullaney** [comment]
Okay which geth is now gving me `/Users/simonmullaney/Desktop/quorum/build/bin/geth`

I tried setting up the QNM again, but I'm still got the same error in  `communicationNode.log`

**Comment by coeniebeyers** [comment]
Are you doing the `which geth` from the same terminal as the one where you are running `node index.js` ? It might be that the PATH on one is correct but not on the other

**Comment by simonmullaney** [comment]
Yes, but I ssh into a virtual ubuntu machine which has the five steps done that are outlined in the `README.md` 
1. mkdir workspace && cd $_
2. wget https://raw.githubusercontent.com/ConsenSys/QuorumNetworkManager/master/setup.sh
3. chmod +x setup.sh
4. ./setup.sh
5. source ~/.bashrc

My terminal output:

Simons-MacBook-Pro:quorum simonmullaney$ which geth
/Users/simonmullaney/Desktop/quorum/build/bin/geth
Simons-MacBook-Pro:quorum simonmullaney$ ssh simon@13.82.93.101
simon@Node1:~$ cd workspace/QuorumNetworkManager/
simon@Node1:~/workspace/QuorumNetworkManager$ node index.js
Trying to get public ip address, please wait a few seconds...
Welcome! 

Please enter the IP address other nodes will use to connect to this node. 

Also, please enter a publicly identifyable string for this node to use.


prompt: localIpAddress:  (13.82.93.101) 
prompt: nodeName:  node1
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
prompt: option:  1
[*] Starting new node...
Generating node key

enode: enode://963b26bf48cb988517fbc3a416906dc2b359b3b8010938682c36d2fa82779951c199b9831d93c605ce62713e3014cde2c8a555b62cd47ebe26b53eae50e877b8@13.82.93.101:20000?raftport=40000

[*] Starting communication node...

**Comment by coeniebeyers** [comment]
I was assuming you have been doing everything on the vm. You will need to reinstall geth on your mac, if you want to use geth on your mac.

Once you are ssh'ed in, what is the output of `which geth`? It needs to point to where quorum is installed (`workspace/quorum/build/bin/geth`).

**Comment by simonmullaney** [comment]
Got it sorted Thanks a million for your help :)
